### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Kamelmat-Maps-Practice-2#1]
# Revisión
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen ejercicio @kamelmat  ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- ¡Muy bien resuelto el proyecto!... poco que añadir tengo.

**Comment by kamelmat** [comment]
### Gracias EDU!🦾
